# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ai_model.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61i_model.proto\x12\nscanner_ai\"\x0b\n\tAIInitReq\"1\n\tAIInitRes\x12$\n\x06result\x18\x01 \x01(\x0e\x32\x14.scanner_ai.AIResult\"\xa2\x01\n\x12\x41IPredictSampleReq\x12\n\n\x02id\x18\x01 \x01(\r\x12\x19\n\x11sampling_rate_khz\x18\x02 \x01(\r\x12\x17\n\x0f\x63\x65nter_freq_khz\x18\x03 \x01(\r\x12\x0e\n\x06\x62w_khz\x18\x04 \x01(\r\x12\x12\n\nnum_chunks\x18\x05 \x01(\r\x12\x13\n\x0boverlay_khz\x18\x06 \x01(\r\x12\x13\n\x0bsamples_len\x18\x07 \x01(\r\"F\n\x12\x41IPredictSampleRes\x12\n\n\x02id\x18\x01 \x01(\r\x12$\n\x06result\x18\x02 \x01(\x0e\x32\x14.scanner_ai.AIResult\".\n\x0f\x41ISampleDataReq\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0f\n\x07samples\x18\x02 \x03(\x02\"W\n\x0f\x41ISampleDataRes\x12\n\n\x02id\x18\x01 \x01(\r\x12\x11\n\tlte_freqs\x18\x02 \x03(\x02\x12\x12\n\numts_freqs\x18\x03 \x03(\x02\x12\x11\n\tgsm_freqs\x18\x04 \x03(\x02\"\xb8\x01\n\nAIModelReq\x12)\n\x08init_req\x18\x01 \x01(\x0b\x32\x15.scanner_ai.AIInitReqH\x00\x12<\n\x12predict_sample_req\x18\x02 \x01(\x0b\x32\x1e.scanner_ai.AIPredictSampleReqH\x00\x12\x36\n\x0fsample_data_req\x18\x03 \x01(\x0b\x32\x1b.scanner_ai.AISampleDataReqH\x00\x42\t\n\x07message\"\xb8\x01\n\nAIModelRes\x12)\n\x08init_res\x18\x01 \x01(\x0b\x32\x15.scanner_ai.AIInitResH\x00\x12<\n\x12predict_sample_res\x18\x02 \x01(\x0b\x32\x1e.scanner_ai.AIPredictSampleResH\x00\x12\x36\n\x0fsample_data_res\x18\x03 \x01(\x0b\x32\x1b.scanner_ai.AISampleDataResH\x00\x42\t\n\x07message*J\n\x08\x41IResult\x12!\n\x1d\x41I_RESULT_SUCCESS_UNSPECIFIED\x10\x00\x12\x1b\n\x17\x41I_RESULT_ERROR_UNKNOWN\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_model_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AIRESULT']._serialized_start=842
  _globals['_AIRESULT']._serialized_end=916
  _globals['_AIINITREQ']._serialized_start=30
  _globals['_AIINITREQ']._serialized_end=41
  _globals['_AIINITRES']._serialized_start=43
  _globals['_AIINITRES']._serialized_end=92
  _globals['_AIPREDICTSAMPLEREQ']._serialized_start=95
  _globals['_AIPREDICTSAMPLEREQ']._serialized_end=257
  _globals['_AIPREDICTSAMPLERES']._serialized_start=259
  _globals['_AIPREDICTSAMPLERES']._serialized_end=329
  _globals['_AISAMPLEDATAREQ']._serialized_start=331
  _globals['_AISAMPLEDATAREQ']._serialized_end=377
  _globals['_AISAMPLEDATARES']._serialized_start=379
  _globals['_AISAMPLEDATARES']._serialized_end=466
  _globals['_AIMODELREQ']._serialized_start=469
  _globals['_AIMODELREQ']._serialized_end=653
  _globals['_AIMODELRES']._serialized_start=656
  _globals['_AIMODELRES']._serialized_end=840
# @@protoc_insertion_point(module_scope)
